### ISSUE TITLE
Incorrect detection of Risu mentions in Japanese

### ISSUE THREAD

**Issue by BrandtnerKPW** [luna-translations-bot/luna-translations-bot#10]
On the Ayunda Risu fanserver Luna TL bot periodically posts mentions to Risu in Japanese, finding "リス" as part of other words. Most often it is "リスナー" and "プリスキン" in Luna's stream.
I didn't find how to filter it myself, so If possible, please add these 2 words to the block list for mentions to Risu.

![изображение](https://user-images.githubusercontent.com/44533871/211206150-f7b6aff0-4eef-45eb-96b5-25bcbfdc34a8.png)

![изображение](https://user-images.githubusercontent.com/44533871/211206160-9ab3ff2b-e05e-4720-994c-6d487bde96b4.png)

**Comment by tam-carre** [comment]
@BrandtnerKPW I've removed リス from Risu's alias list.

**Comment by tam-carre** [comment]
30ae87b84c6f3399ca062a05be63750c53744811
